### ISSUE TITLE
Show/ Hide not functioning at all (b24)

### ISSUE THREAD

**Issue by Millicant** [BattleScribe/iOS-Alphas#10]
So far, this feature isn't doing anything in iOS. Everything is visible and it seems that the show/hide modifiers are not kicking errors.

**Comment by Jonskichov** [comment]
This is because all the modifiers are up the creek. No idea why. I'm suspecting it's the build tools...

I tested by reverting back to build 22 and they weren't working there either.

Closing in favour of your other issue: https://github.com/BattleScribe/iOS-Alphas/issues/17
