### ISSUE TITLE
Build 24 - iPad Force Creation Display

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#11]
This is an unusual one to explain, so a pic will be handier. It's as if the left hand margin is placed very far to the left. This happens on iPad with both Catalogue and Force Org selections. If the iPad is in Landscape mode, it is even worse, you can't even see part of the Catalogue names.

![2016-06-15 21 58 04](https://cloud.githubusercontent.com/assets/4388344/16271883/f0ce6d32-3858-11e6-92fb-ce4b4b8e5d73.png)

![2016-06-22 08 09 14](https://cloud.githubusercontent.com/assets/4388344/16271961/388803fe-3859-11e6-8083-227d8e1c8d03.png)

**Comment by Jonskichov** [comment]
Fixed in build 28: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-228627672
