### ISSUE TITLE
Build 24 - Downloading Data - Cosmetic

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#12]
The spinny wheel is off center when downloading data. Low priority bug, but it just looks a bit unpolished. 

![2016-06-14 19 03 27](https://cloud.githubusercontent.com/assets/4388344/16272014/70270814-3859-11e6-91a0-1f0f1f896a6c.png)
![2016-06-14 19 28 18](https://cloud.githubusercontent.com/assets/4388344/16272019/71f81b10-3859-11e6-9ccb-25c2b809ef93.png)

**Comment by ibrAmGaunt** [comment]
Not just the downloading data spin wheel, but any loading wheel screen is off centre.

**Comment by Jonskichov** [comment]
Fixed in build 28: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-228627672

**Comment by Kohato** [comment]
Not fully fixed in build 28.

"Importing Data" when connecting a BSI is still off centered.  The rest of the instances are fixed though.
