### ISSUE TITLE
Strange bar on iPad// iOS 10 Beta 1

### ISSUE THREAD

**Issue by Bettarg** [BattleScribe/iOS-Alphas#16]
Hello. 

There is a strange Bar on the Army Roster. 
In landscape it's gone 🤔
![img_0109](https://cloud.githubusercontent.com/assets/17293490/16304153/7891533c-3954-11e6-8283-80eb67a2d2f8.PNG)

**Comment by Jonskichov** [comment]
Fixed in build 28: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-228627672
