### ISSUE TITLE
Modifiers not working at all (b25)

### ISSUE THREAD

**Issue by Millicant** [BattleScribe/iOS-Alphas#17]
It seems that no modifiers are operating correctly. This may be simply a greater issue than my "hide" modifiers not working. I think none of them are. 

Take a look at the LACAL for examples, nothing is working correctly.

**Comment by Jonskichov** [comment]
@Millicant is this also a problem on desktop? I'm seeing legion-specific stuff showing/hiding appropriately there.

**Comment by Jonskichov** [comment]
No idea whats going on here. Everything is fine on Desktop/Android.

Can you confirm if this has ever worked on iOS? I reverted back to build 22 and nothing was working there either.

Currently I am suspecting my build tools - I had an update to Xamarin a few days ago... :/

**Comment by Jonskichov** [comment]
Fixed in build 27: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-228541212
