### ISSUE TITLE
Cosmetic: Build 28 - Force Title too high up

### ISSUE THREAD

**Issue by Kohato** [BattleScribe/iOS-Alphas#18]
In build 28 the name of the chosen force is a bit too high, it's getting nearly concealed by the army list name.
![image1](https://cloud.githubusercontent.com/assets/16939161/16379544/bfc53634-3c37-11e6-9580-15ec4d2c07e7.PNG)

**Comment by Jonskichov** [comment]
Looks like you're not scrolled all the way to the top...?

I'm not seeing this in test. Can you tell me the version of iOS and what device this is on?

**Comment by Kohato** [comment]
Hah that would be embarrassing. I can't reproduce now. I choose to say you fixed it in build 30 instead of admitting I'm blind. :)

**Comment by Kohato** [comment]
9.3.2 on a 6s if you care to investigate but I think we're good here :)
