### ISSUE TITLE
Build 28 - specific event causing crashing

### ISSUE THREAD

**Issue by ibrAmGaunt** [BattleScribe/iOS-Alphas#19]
Using Horus Heresy Scribe file, created a space marine legion list, added "fortifications" to forces, tried to add any of the fortification options and BS crashes to phone home screen.

iPhone 6

Email me if any further info is needed.

Tristian

**Comment by Jonskichov** [comment]
Fixed in build 31: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-229836545
