### ISSUE TITLE
Adding Units/Formations/Etc

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#2]
When you click on the + to add something to a category (HQ, Elite, Heavy, etc) it will list most things as 0 points if the base listing has no points. 

Example: KDK Possessed are 150 points per unit. They are pointed as 30 points per model, 5 model minimum. In the main roster view, they show up as 150 pts. In the screen to add Elites, they show as 0 points.

**Comment by Jonskichov** [comment]
Fixed in build 23: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-226953445
