### ISSUE TITLE
(B36) Restoring in app purchase times out

### ISSUE THREAD

**Issue by ibrAmGaunt** [BattleScribe/iOS-Alphas#23]
Downloaded the new update, on opening it asked for my Apple ID, then tryed to restore app purchase, spin wheel for aprox 2 min then app opens to main screen with a bubble saying "restoring app purchases timed out" 

iPhone 6, build 36 BS(2)

**Comment by ibrAmGaunt** [comment]
Still an existing issue in build 37, but the speed to reach the "timed out" screen has become significantly faster. Don't know if that's a good sign or not? 
Example times:
b36 aprox 1 minute 
B37 aprox 20 seconds.

**Comment by Jonskichov** [comment]
Fixed in build 38: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-235622840

**Comment by BrianisBlack** [comment]
This appears to still be an issue in build 38.  While the app no longer times out when attempting to restore previous purchases, it attempts to restore purchases each time I return to the View Roster page.  This takes approximately 1-2 minutes.

iOS v9.3.2, iPhone 6s+
