### ISSUE TITLE
Restore Purchases Always Attempts on Roster List Page

### ISSUE THREAD

**Issue by BrianisBlack** [BattleScribe/iOS-Alphas#24]
I believe issue #23 is still present in build 38 to some extent.  Instead of timing out, the client takes a significant amount of time before abandoning the attempt to restore purchases every time the client is opened and also occurs every time the user returns to the roster list screen from another page.  This is on an iPhone 6s+, running iOS 9.3.2.

**Comment by Jonskichov** [comment]
No longer an issue in build 39: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-244511047
