### ISSUE TITLE
Google sign in now failing and all roster data deleted or can't be accessed?!

### ISSUE THREAD

**Issue by ibrAmGaunt** [BattleScribe/iOS-Alphas#27]
I don't know if the the 2 issues are connected but I got an error page come up when signing in to BS (pic below). And all my army rosters have ether been deleted or can't be accessed without a sign in?

Up to date on my build, and still just using my IPhone 6.

![image](https://cloud.githubusercontent.com/assets/20018049/18698730/539e0610-7f81-11e6-841f-1858fa1117be.png)

**Comment by Jonskichov** [comment]
Should be fixed in build 48: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-250439120
