### ISSUE TITLE
Error opening roster

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#4]
When using data files in the new BS2 repo (that do work on PC) it will delete the file with the following: 

![2016-06-13 22 49 59](https://cloud.githubusercontent.com/assets/4388344/16031570/d9609120-31b9-11e6-9fd7-64ca5c08f3d9.png)

Can somebody confirm if this works on Android?

**Comment by Jonskichov** [comment]
Not been able to reproduce on Android or Desktop.

There have been some new builds since you raised this, is it still an issue?

(I'll try again on iOS after this stupid-long build process completes :/)

**Comment by cartag** [comment]
This was still an issue in build 23

**Comment by cartag** [comment]
This is only for info that is already converted to 2.0, rather than syncing to the 1.15 repo

**Comment by cartag** [comment]
Still present in build 24 on iPhone. It will sync the 1.15 data and allow me to use that, but anything already converted doesn't work.

**Comment by cartag** [comment]
Fixed on my end. Data file synced wasn't working version, PC version more tolerant to certain catalogue bugs, which is a good thing in this case since it led us to more info about the iOS version :)
