### ISSUE TITLE
Cannot sync data to iPad - jailbroken 9.0.2

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#5]
iPad will not sync files from regular site. 

Have removed item in data list, re downloaded, same result.
Deleting data, deleting app, redownloading v20, adding index.bsi, will not download.

**Comment by Jonskichov** [comment]
Hm, I've not done anything to specifically block/interfere with jailbroken devices. Though I don't have one to test with... 

To be honest, I'm not going to go out of my way to support them either.

One thing that does spring to mind was this Reddit post I had a while back: https://www.reddit.com/r/BattleScribe/comments/4bk5ty/ipad_battlescribe_will_not_load_my_roster_data_it/

Take a look and see if it helps.

**Comment by cartag** [comment]
The jailbreak probably had nothing to do with it, it syncs fine on my iPhone, same version and also jailbroken

**Comment by cartag** [comment]
Figured out the problem, unrelated to the app.
