### ISSUE TITLE
BS2 Alpha v23 crashing before opening new list.

### ISSUE THREAD

**Issue by ibrAmGaunt** [BattleScribe/iOS-Alphas#6]
Just started occurring today, updates to newest alpha file and I cannot create new list. I was able to work list yesterday.

Info for re-creation:
iPhone 6, up to date iOS, BS2 v23 (or at least most current as of June 18/16)

Steps:
Open app> downloaded Horus Heresy Scribe file from Batlescribe forums> select space marine legions for army> see "retrieving scribe files screen for aprox 15 seconds> crash to iPhone home screen.

If more details needed email me @ Tristian_at_work@hotmail.com

**Comment by Jonskichov** [comment]
Fixed in build 24: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-227626956
