### ISSUE TITLE
Build 24 - Force creation

### ISSUE THREAD

**Issue by cartag** [BattleScribe/iOS-Alphas#9]
When creating a new roster, it automatically asks you to Select Catalogue. After this is chosen, it then goes to Force Org. 

If you back out of Force Org, it then goes to a blank screen with "**Forces** | Details" at the top with "<- Create Roster"

When changing from Forces to Details and back again it will then have the + in the bottom right to add a new force.

**Comment by Jonskichov** [comment]
Fixed in build 31: https://github.com/BattleScribe/iOS-Alphas/issues/1#issuecomment-229836545
